[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
metf = "5jB9vrwJC28KUgZfBoQPhpnKq7deSMzCNeDvoPrAzNv6"
transfer-hook = "2TJHnk4FMjMXDLYwS6MiSXBEEBGJtqXejnPZzoyGpZC6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest --skip-nx-cache"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "tests/token_2022_program.so"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
